Fix bit rot in authconfig, sysctl playbook bits
I'm not sure how the sysctl stuff was working before, this complained about `file` not being a valid parameter:

```
TASK [host-basics : Activate sysctl to avoid CVE-2019-1147] *******************************************************
fatal: [freezingsaddles.org]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (sysctl) module: file Supported parameters include: ignoreerrors, name, reload, state, sysctl_file, sysctl_set, value"}
```

The tagging indent was off for that too.

The ansible `authconfig` module does not seem to work with recent CentOS 7 releases, so we fall back to using `command` instead. Here is the error it was emitting:
```
fatal: [freezingsaddles.org]: FAILED! => {"changed": false, "module_stderr": "Shared connection to freezingsaddles.org closed.
", "module_stdout": "Traceback (most recent call last):
  File \"/var/spool/ansible/.ansible/tmp/ansible-tmp-1578005014.19-9405914775017/AnsiballZ_authconfig.py\", line 102, in <module>
    _ansiballz_main()
  File \"/var/spool/ansible/.ansible/tmp/ansible-tmp-1578005014.19-9405914775017/AnsiballZ_authconfig.py\", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/var/spool/ansible/.ansible/tmp/ansible-tmp-1578005014.19-9405914775017/AnsiballZ_authconfig.py\", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.authconfig', init_globals=None, run_name='__main__', alter_sys=True)
  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module
    fname, loader, pkg_name)
  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code
    exec code in run_globals
  File \"/tmp/ansible_authconfig_payload_xx8yoh/ansible_authconfig_payload.zip/ansible/modules/authconfig.py\", line 602, in <module>
    self.printError(_(\"--enablerequiresmartcard is not supported for module 'sssd', option is ignored.\"))
  File \"/tmp/ansible_authconfig_payload_xx8yoh/ansible_authconfig_payload.zip/ansible/modules/authconfig.py\", line 613, in <module>
    self.retval = 3
NameError: name 'Authconfig' is not defined
", "msg": "MODULE FAILURE
See stdout/stderr for the exact error", "rc": 1}
```